#! /bin/sh

# hyprctl keyword windowrule "workspace 6 silent,caprine" && hyprctl dispatch exec "caprine"
# hyprctl keyword windowrule "workspace 6 silent,webcord" && hyprctl dispatch exec "webcord"
hyprctl keyword windowrule "workspace 1 silent,kitty" && hyprctl dispatch exec "kitty ~"
hyprctl keyword windowrule "workspace 2 silent,google-chrome-stable" && hyprctl dispatch exec '/opt/google/chrome/google-chrome "--profile-directory=Profile 2"' 
# hyprctl keyword windowrule "workspace 6" && hyprctl dispatch exec '/opt/google/chrome/google-chrome "--profile-directory=Profile 2" --app-id=magkoliahgffibhgfkmoealggombgknl' 
# hyprctl keyword windowrule "workspace 6 silent,kitty" && hyprctl dispatch exec /opt/google/chrome/google-chrome "--profile-directory=Profile 2" --app-id=magkoliahgffibhgfkmoealggombgknl

# hyprctl keyword windowrule "workspace special silent,kitty" && hyprctl dispatch exec "kitty"

sleep 15

hyprctl keyword windowrule "unset,Electron"
# hyprctl keyword windowrule "unset,Caprine"
hyprctl keyword windowrule "unset,kitty"
#hyprctl reload
