#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
echo "xdg-desktop-portal-hyprland killed"
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
